trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'k8s-dev'

stages:  
  - stage: UpdateGitOps
    displayName: Update GitOps Repo (image tag)    
    jobs:
    - job: Update
      # pool:
      #   vmImage: 'ubuntu-latest'
      steps:
      - checkout: none
      - task: Bash@3
        displayName: Clone GitOps repo
        inputs:
          targetType: inline
          script: |
            git config --global user.email "santosh.mohapatra25@gmail.com"
            git config --global user.name "Santosh Mohapatra"
            git clone https://github.com/santosh-gh/k8s-19-deployment.git
            cd k8s-19-deployment
            git checkout main
            
            git add .
            git commit -m "Updated "
            git push origin main