trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'k8s-dev'
- name: chartName 
  value: 'storehelmchart'
  
stages:
  - stage: Publish
    displayName: Publish Artifact
    jobs:
      - job: PublishArtifact
        displayName: Publish Artifact
        steps:
          - task: PublishPipelineArtifact@1
            displayName: Publish Manifest
            inputs:
              artifactName: $(chartName)
              path: $(chartName)

  - stage: Deploy
    jobs:
    - deployment: DeployAKS
      displayName: Deploy AKS
      environment: $(environment)
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: $(chartName)

              - script: |
                  echo "Workspace Directory: $(Pipeline.Workspace)"
                  ls -R "$(Pipeline.Workspace)"

              - task: AzureCLI@2
                displayName: Get AKS Credentials
                inputs:
                  azureSubscription: $(serviceConnection)
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                    echo "Getting AKS credentials..."
                    az aks get-credentials --name $(aksCluster) --resource-group $(aksResourceGroup) --overwrite-existing

              - task: HelmDeploy@1
                displayName: Helm Upgrade/Install
                inputs:
                  connectionType: 'Azure Resource Manager'
                  azureSubscription: $(serviceConnection)
                  azureResourceGroup: $(aksResourceGroup)
                  kubernetesCluster: $(aksCluster)
                  namespace: $(namespace)
                  command: upgrade
                  chartType: FilePath
                  chartPath: '$(Pipeline.Workspace)/$(chartName)/rabbitmq'
                  releaseName: 'rabbitmq'
                  install: true
                  waitForExecution: false                  