trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'k8s-dev'
- name: imageTag
  value: '3.13'
- name: imageName
  value: 'rabbitmq'

stages:
  - stage: UpdateGitOps
    displayName: Update GitOps Repo
    jobs:
    - job: Update
      # pool:
      #   vmImage: 'ubuntu-latest'
      steps:
      - checkout: none
      - task: Bash@3
        displayName: Clone GitOps repo
        inputs:
          targetType: inline
          script: |
            git config --global user.email "santosh.mohapatra25@gmail.com"
            git config --global user.name "Santosh Mohapatra"
            git clone https://github.com/santosh-gh/k8s-19-deployment.git
            cd k8s-19-deployment
            git checkout main
            
            # Update env values file (YQ preferred, but sed works if format is stable)        
            sed -i 's/\(tag:\s*\).*/\1$(imageTag)/' multi-helmchart/$(imageName)/values.yaml

            git add .
            git commit -m "Updated $(imageName) with Tag: $(imageTag)"
            git push origin main